services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: hn
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
    volumes:
      - hdfs_namenode:/hadoop/dfs/name

  datanode:
    image: apache/hadoop:3.4.1
    container_name: dn
    hostname: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - namenode
    ports:
      - 9864:9864
    volumes:
      - hdfs_datanode:/hadoop/dfs/data

  spark:
    build: .
    container_name: spark
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./src:/app/src
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  hdfs_namenode:
  hdfs_datanode:
