services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hn
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9870:9870
    volumes:
      - hdfs_namenode:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: dn
    environment:
      - SERVICE_PRECONDITION=hn:9870
    depends_on:
      - namenode
    ports:
      - 9864:9864
    volumes:
      - hdfs_datanode:/hadoop/dfs/data

  spark:
    build: .
    container_name: spark
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./src:/app/src
    entrypoint: ["/bin/bash", "-c", "cd /app && tail -f /dev/null"]

volumes:
  hdfs_namenode:
  hdfs_datanode:
